name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set Version Var
      id: fetch-version
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Create Application Package
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src

    - name: Create Release Archive
      uses: vimtor/action-zip@v1.1
      with:
        files: src/dist/windows/D2Macros
        dest: release.zip
        
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Release-${{ steps.fetch-version.outputs.sha_short }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}